name: Ubuntu

on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  build_json-ci_image:
    runs-on: ubuntu-latest
    container: ghcr.io/nlohmann/json-ci:v2.3.0
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: json-ci_image:latest
          outputs: type=docker,dest=/tmp/json-ci_image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: json-ci_image
          path: /tmp/json-ci_image.tar

  ci_test_clang:
    runs-on: ubuntu-latest
    needs: build_json-ci_image
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: json-ci_image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/json-ci_image.tar
      - uses: actions/checkout@v3
      - name: cmake
        run: cmake -S . -B build -DJSON_CI=On
      - name: build
        run: cmake --build build --target ci_test_clang

  ci_test_gcc:
    runs-on: ubuntu-latest
    needs: build_json-ci_image
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: json-ci_image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/json-ci_image.tar
      - uses: actions/checkout@v3
      - name: cmake
        run: cmake -S . -B build -DJSON_CI=On
      - name: build
        run: cmake --build build --target ci_test_gcc
