name: Ubuntu

on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  ci_test_compilers:
    runs-on: ubuntu-latest
    container: ghcr.io/nlohmann/json-ci:v2.2.0
    strategy:
      matrix:
        compiler: [g++-11, g++-latest, clang++-12, clang++-13, clang++-14]
    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: cmake -S . -B build -DJSON_CI=On
      - name: build
        run: cmake --build build --target ci_test_compiler_${{ matrix.compiler }}

  ci_test_standards:
    runs-on: ubuntu-latest
    container: ghcr.io/nlohmann/json-ci:v2.2.0
    strategy:
      matrix:
        standard: [11, 14, 17, 20]
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: cmake -S . -B build -DJSON_CI=On
      - name: build
        run: cmake --build build --target ci_test_${{ matrix.compiler }}_cxx${{ matrix.standard }}
